### PR TITLE
docs: add about-us section in README.md

### LINKED ISSUE #4: Copy and enhance About US section in the Website to the repo
# Request
1. Copy everything under the About US except Board of Leaders. (It is a holder place at the moment)
2. Suggest, if you feel like, where to put Mentors and Board of Leaders.
3. Suggest where to put the Mission section or even merge it with the README summary.

# Suggestion
Add everything under "About US" in the [website](https://www.activecourses.tech/) into the repo.

As where  to add it, I personally think that only mentors and Board of Leaders should be at the top in the [README](https://github.com/OmarShawky1/ACU/blob/main/README.md). Meanwhile, the rest should be in the [Explanation beside ACU Comparison](https://github.com/OmarShawky1/ACU/blob/main/README-Explanation.md#acu-comparison) or like in OSSU, at the bottom of the README.

### PR DESCRIPTION
**Pull request by hulxv**
Closes #4

### CODE REVIEW

**Comment by OmarShawky1** [comment]
# Requested changes
1. The order of "About Us" is: Board of Leaders, Mentors, Curriculum Maintainers, Contributors. Please maintain  same order.
2. Switch back all style changes. (Maybe do another PR with it if you want). you can save them locally using `git stash` if you are not familiar with git.

**Comment by hulxv** [comment]
Is there anything else should I do?

**Comment by OmarShawky1** [comment]
@Hulxv 
Excellent work. 2 things that can even make it more excellent.
1. In table, use `|:-:|` to center text in table. you don't need to use more than `-`.
2. Try to use [logos from website](https://github.com/alikehel/activecourses/blob/main/static/img/github-black.svg) instead of text.

If you don't want to do it, then this is fine and I will do it myself :)

**Comment by hulxv** [comment]
@OmarShawky1

**Comment by OmarShawky1** [comment]
Fixed in #4

**Pull request closed without merging**
